# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

application_url = "https://dev.request-quote.online"
client_id = "b6c35f1f28ca75c5a862b0a79daaaddd"
embedded = true
name = "Quote form & price hiding"

[build]
automatically_update_urls_on_dev = false
dev_store_url = "shopnest-10051.myshopify.com"

[webhooks]
api_version = "2026-01"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/webhooks"



[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
optional_scopes = []
scopes = "write_app_proxy,read_customers,write_draft_orders,write_products,read_themes"
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://dev.request-quote.online/api/auth/callback",
]

[app_proxy]
prefix = "apps"
subpath = "request-quote"
url = "https://dev.request-quote.online/api"

[pos]
embedded = true

[shop.metafields.app.show_on_all]
name = "Show quote globally"
type = "boolean"

[shop.metafields.app.show_on_all.access]
admin = "merchant_read_write"
storefront = "public_read"

# Billing is managed via the Shopify Partner Dashboard for Managed Pricing. 
# Refer to: Distribution > Shopify App Store listing > Manage listing > Pricing content.
